### ISSUE TITLE
Be able to run models whose compiled SQL include `_dbt_max_partition`

### ISSUE THREAD

**Issue by alvfermar-mp** [autotraderuk/dbt-dry-run#10]
I am starting to use the package to do dry run of out models in BQ, and I haven't been able to run many of them, as I receive the error `Unrecognized name: _dbt_max_partition at [<line>:<column>]`. The issue seems to boil down to the fact that many of our models are incremental and make use of that variable, which still appears unrendered in the `compiled_sql` key of the model in the `manifest.json` file. Consider a model like:
```
WITH source_table AS (
  SELECT
    field1
    , field2
    , field3
  FROM
    (
      SELECT
        *
      FROM a_source_table 
      WHERE DATE(partition_field) >= DATE_SUB(DATE(_dbt_max_partition), INTERVAL 2 day)  
    )
  )
SELECT 
  *
FROM source_table
```
The compiled_sql of the model will still have that `_dbt_max_partition` variable and thus when running the query with the CLI it will fail. I think simple way to fix that would be replacing that with a timestamp / date literal, or with a function like `CURRENT_TIMESTAMP()` or `CURRENT_DATE()`

**Comment by connor-charles** [comment]
Looking at how `dbt-bigquery` [declares this variable](https://github.com/dbt-labs/dbt-bigquery/blob/f634a57282c47861db6b68b0acba624d80dce405/dbt/include/bigquery/macros/materializations/incremental.sql#L1) I think this can be fixed by prepending the compiled SQL for incremental models with a dummy variable declaration in the `_modify_sql` method in the `ModelRunner` class. This is how the materialisation declares `_dbt_max_partition`:

```
{% macro declare_dbt_max_partition(relation, partition_by, sql) %}

  {% if '_dbt_max_partition' in sql %}

    declare _dbt_max_partition {{ partition_by.data_type }} default (
      select max({{ partition_by.field }}) from {{ this }}
      where {{ partition_by.field }} is not null
    );

  {% endif %}
{% endmacro %}
```

I can't imagine for dry running the exact value of the max partition would be important so I think I agree that just setting this to any arbitrary timestamp is fine. The function you would need to modify is [here](https://github.com/autotraderuk/dbt-dry-run/blob/3d0a8c8755c5bd04c45571dfaf371a727b437f59/dbt_dry_run/node_runner/model_runner.py#L76), we just need another check that if the model is incremental then prepend the variable declaration to something like:

`declare _dbt_max_partition {{node.config.partition_by.data_type}} default (CURRENT_TIMESTAMP());`

**Comment by alvfermar-mp** [comment]
I will pick this up, thanks for the clarifications!
