### ISSUE TITLE
False positive if column type of incremental changes

### ISSUE THREAD

**Issue by davidsr2r** [autotraderuk/dbt-dry-run#26]
### Incremental Merge Incompatibility

**Description**

We've noticed that dbt-dry-run isn't picking up schema incompatibility that comes up in production when an incremental model with on_schema_change not set (defaulting to ignore) runs its merge step, e.g. column name changes, type changes, generally incompatible schema changes. We're happy to provide examples, but any breaking schema change being checked by dbt-dry-run and then run against an existing incremental model without an on_schema_change setting (defaulting to ignore) should reproduce the issue.

We also see the issue arising when an incremental table has a column whose name changes and a downstream incremental table that fails to update its column selection will work when it is dry run since it is checked against the production schema.

**Reproduction Guide**
A quick minimal example is first creating the following table, targeting production:

```sql
{{ config(
    materialized="incremental",
    incremental_strategy = 'insert_overwrite',
    partition_by = {'field': 'CurrentTimestamp', 'data_type': 'timestamp', 'granularity': 'day'}
) }}

SELECT
  TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY) AS CurrentTimestamp,
  TIMESTAMP("2022-01-01 23:57:12.120174") AS ATimeStamp
```

And then (a) making sure that dbt-dry-run works and doesn't complain, then (b) making the following changes:

```diff
{{ config(
    materialized="incremental",
    incremental_strategy = 'insert_overwrite',
    partition_by = {'field': 'CurrentTimestamp', 'data_type': 'timestamp', 'granularity': 'day'},
) }}

SELECT
- TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY) AS CurrentTimestamp,
+ CURRENT_TIMESTAMP() AS CurrentTimestamp,
- TIMESTAMP("2022-01-01 23:57:12.120174") AS ATimeStamp
+ DATE(TIMESTAMP("2022-01-01 23:57:12.120174")) AS ATimeStamp
```
Then (c) running dbt-dry-run again, to see that it doesn't pick this issue up, then (d) running via dbt to production to see:
Query error: Value has type DATE which cannot be inserted into column ATimeStamp, which has type TIMESTAMP

You can get the same result with, for example, changing the name of a column or adding a sub-column to a STRUCT.

**Comment by connor-charles** [comment]
This is caused by the dry runner only running the `SELECT` statement for incremental not the full materialisation code which includes the merge/insert statement etc. We could fix this by trying to see if we can add more of the materialization code into the query we dry run (Similar to what we did with views where we add `CREATE OR REPLACE VIEW` in the [ModelRunner code](https://github.com/autotraderuk/dbt-dry-run/blob/804c7fbe7a84e350bd17cad7f333c9decb4d80a9/dbt_dry_run/node_runner/model_runner.py#L85). That might cause problems where the query planner doesn't return the predicted schema anymore but it is worth looking into.

Does this happen for all incremental strategies?

**Comment by davidsr2r** [comment]
We haven't tested for other incremental strategies, but we're pretty married to ours. 

Happy to test others and report back after the holiday period :)

**Comment by davidsr2r** [comment]
I had a lovely break down on the coast, I hope you had a lovely white Christmas up in the UK :) 

Yep yep, we're using the insert_overwrite strategy, to minimise on cost and execution time, which we already struggle with & will want to address in the future.

**Comment by connor-charles** [comment]
I am going to try and at least get a failing integration test for this. Will need to work on some extra functionality to the test suite to be able to persist incremental tables with some dummy data in the Big Query project it is running against.

**Comment by connor-charles** [comment]
Managed to get a failing [integration test ](https://github.com/autotraderuk/dbt-dry-run/blob/13938eb1ec5f68742dfc7133e8d54c381f5b6ae7/integration/projects/test_incremental/test_incremental.py#L42 )that highlights the problem.

I have played around with pulling in more logic from the incremental materialization to run the merge statement to get BigQuery to throw the error with mixed success:

```python
        if node.config.materialized == "incremental" and self._sql_runner.node_exists(node):
            sql_statement = f"""
            merge into {node.to_table_ref_literal()} as DBT_INTERNAL_DEST
            using (
                {sql_statement}
            ) as DBT_INTERNAL_SOURCE
            on FALSE
            when not matched by source
            then delete
            """
```

Here `sql_statement` is the `select` statement that is present in the incremental model. This kinda works but breaks the `on_schema_change` stuff because the `merge into` statement always returns the schema of the table that is present in the target environment.

The way dbt handles this is by first doing the schema migration then running the merge statement. But we can't change the schema of the node in the target because then it wouldn't be a dry run.

I am keen to fix this though as we have recently had a production failure that was not caught due to this issue 👍

**Comment by zachary-povey** [comment]
Hey @ccharlesgb - just been caught out with this one too so keen to get involved with a fix if possible. 

I think any solution will need to check the value of `on_schema_change` and run some slightly different sql in each case in order to mirror what would pass/fail in dbt. Just been mapping out in my head the different permutations  and have this as a rough idea of what the desired behaviour is:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/zacharypovey/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/zacharypovey/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



  | ignore | fail | append_new_columns | sync_all_columns
-- | -- | -- | -- | --
new columns | pass*  | fail | pass | pass
removed columns | fail | fail | pass* | pass
column type change | fail | fail | fail | pass
schema required by downstreams | target | target | model sql + any missing columns from target | model sql


</body>

</html>

*simply ignored by dbt

Does that look about right to you?

I'm thinking we could maybe tackle this in a few iterations as I think handling `append_new_columns` is going to be far trickier than the other three so maybe for that case we could just treat it the same as `sync_all_columns` and emit a warning  to begin with? Then for the other three I think we could:
- use current behaviour for `sync_all_columns` 
- add merge statement for ignore & fail (will need to tweak this conditionally for fail vs ignore to ensure we get the correct behaviour for each when the select has extra columns in it)

Let me know your thoughts!

**Comment by zachary-povey** [comment]
Hello mate, cheers for getting back!

>This kinda works but breaks the on_schema_change stuff because the merge into statement always returns the schema of the table that is present in the target environment

So yeah what I was getting at was that this schema (the one in the target env) is the correct schema to use in the case that `on_schema_change` is `ignore` or `fail`, as they will either fail, or keep the schema as it is. So I was suggesting, as a first pass, we could use a merge statement for just these cases and keep the existing behaviour for the other `on_schema_change` values, so continue to use the raw select statement, and simply emit a warning where we thought this could fail to catch stuff.

I had thought the existing behaviour would actually be the correct behaviour for `sync_all_columns`, and therefore we could not warn in that case, but based on what you said I think I have misinterpreted what it does (have never actually used it).

I think if/when we try and tackle all cases it is inevitable we will need to run both merge and select statements like you say and neither will give quite the correct schema* so yeah may need to do some manual fiddling with the schemas 😬 . 

Also, might be missing something but think we'd also need to either tweak the merge statement based on `on_schema_change` or have some explicit checks to ensure we correctly mirror dbt pass/failures for column additions/removals too.

---
\*For example, if we have the case that: 
- `on_schema_change=append_new_columns`
- a column is renamed in an incremental model

When dbt runs this is essentially a column addition and a removal so with `append_new_columns` it will add the new column and ignore the missing one. So there:
- desired schema is target + new column
- select statement gives target - old + new
- merge statement gives target

**Comment by zachary-povey** [comment]
Footnote to previous message, on this:
>I don't think sync_all_columns will succeed if the column type changes. 

just tested it and it does succeed for valid type changes. I tested back and forth between int, float and string and it updated the table schema each time to match the schema defined in the `SELECT`.

dbt versions: 
- core=1.5.3
- bigquery=1.5.0

**Comment by ccharlesgb** [comment]
> I think what your suggesting makes sense then - I will have a go at implementing (probably later this week). Worth noting my extra follow up comment below about sync_all_columns though - as this does allow for changing column types we may need different behaviour in that case.

I find this quite surprising that this works. Does it even work for struct types when you add/remove fields to the struct? I don't really see how `sync_all_columns` can coerce a string column (with non numeric strings in it) to a numeric without nulling out old data.

> So I was suggesting, as a first pass, we could use a merge statement for just these cases and keep the existing behaviour for the other on_schema_change values, so continue to use the raw select statement, and simply emit a warning where we thought this could fail to catch stuff.

I still think this is a good idea. If you struggle to get all `on_schema_change` cases working with a merge statement it would be good for the dry run to at least catch the `ignore` and `fail` cases by dry running a merge.

Let me know if you struggle to get the integration tests running on a BQ instance you control. I have only ever got it to run on the AT project.

**Comment by ccharlesgb** [comment]
@zachary-povey Hey, did you manage to get anywhere with this? We've just had a dbt failure from the same issue so would be keen to resolve this as well.

**Comment by zachary-povey** [comment]
Hey mate, no sorry I haven't had a chance and probably won't until next week now realistically. Still happy to have a crack at that point but let me know if you start working on it 👍

**Comment by ccharlesgb** [comment]
Just had a quick play around on this [branch](https://github.com/autotraderuk/dbt-dry-run/commit/d361642e6176802fe6dc57731fec4d8f785f7256)

Dry running a merge statement does work but as we suspected it breaks all the `on_schema_change` stuff:

```python
        if node.config.materialized == "incremental" and self._sql_runner.node_exists(node):
            schema = self._sql_runner.get_node_schema(node)
            values_csv = ",".join([field.name for field in schema.fields])
            sql_statement = f"""
                MERGE {node.to_table_ref_literal()}
                USING (
                  {sql_statement}
                )
                ON True
                WHEN NOT MATCHED THEN 
                INSERT ({values_csv}) 
                VALUES ({values_csv})
            """
```

Modifying the SQL to do a basic merge statement will trigger the error but the problem is the `values_csv` in this case needs to be the intersection of the columns in the table in Big Query (`node.to_table_ref_literal()`) and the columns returned by `sql_statement`. So yer this needs us to do the following:

1. Dry run the SQL statement as normal to get the predicted schema of the incremental's SELECT statement
2. If its an incremental and it exists in BQ then dry run the merge statement with the `values_csv` populated with the intersection of the node schema in BQ and the columns returned by the first dry run to check type compatibility
3. Then apply the `on_schema_change` modifications to the schema in the first dry run as normal

**Comment by ccharlesgb** [comment]
Ok I have managed to get this working. Need to write a few more tests but should be able to get this out next week if nothing comes up with any edge cases

**Comment by zachary-povey** [comment]
Nice one mate! Apologies I never got around to it.
