### ISSUE TITLE
New Feature: Full Refresh Mode

### ISSUE THREAD

**Issue by davidsr2r** [autotraderuk/dbt-dry-run#27]
**Context: Detecting Full Refresh Incompatibility**

Our developers make breaking changes to incremental table schemas then deploy these to production using a full refresh. We want to validate that such a full refresh will work before that deploy step. 

Since dbt-dry-run simulates an incremental run, the model schemas it deals with are variations of the prod schemas, not the schema you would get with a full refresh, meaning it doesn’t tell us about impending failures.

We are thinking of a full refresh option for dbt-dry-run to help us detect these issues.

**Reproduction Guide**
We want two models, table model A and incremental table model B, where B selects directly from A. 
We first run the following two models:
```sql
-- ParentTableA.sql
{{ config(
    materialized="table"
) }}

SELECT
  CURRENT_TIMESTAMP() AS CurrentTimestamp,
  CAST(2 AS INT64) AS AnIntyInt
```

```sql
-- ChildTableB
{{ config(
    materialized="incremental",
    incremental_strategy = 'insert_overwrite',
    partition_by = {'field': 'CurrentTimestamp', 'data_type': 'timestamp', 'granularity': 'day'},
    tags=["incrementals", "daily"]
) }}

SELECT * FROM {{ ref('ParentTableA') }}
```

We then make the following change to Parent A, to simulate a schema update. After this change, when we run both models, the incremental run of Child B will fail, but full refreshes will succeed:
```diff
 -- ParentTableA.sql
{{ config(
    materialized="table"
) }}

SELECT
  CURRENT_TIMESTAMP() AS CurrentTimestamp,
- CAST(2 AS INT64) AS AnIntyInt
+ "2" AS AnIntyInt
```

**Comment by connor-charles** [comment]
I think this is a good feature to add as I think a lot of the dbt community use `--full-refresh` quite a lot but it just isn't something we use at Auto Trader (We tend to use versioning in the table aliases to keep hold of the old data for a while in case anyone is using it downstream).

I had a quick look to see if the manifest contains any hints at wether or not it says if the manifest was compiled with `--full-refresh` but it does not so we will need to add a CLI parameter to `dbt-dry-run` that you will have to make sure that you keep the `dbt compile` command consistent with. So if you compile with `--full-refresh` you have to remember to dry run wil `--full-refresh` otherwise you will get weird results.

There also seems to be a [config option](https://docs.getdbt.com/reference/resource-configs/full_refresh#description) to control if individual models should `full_refresh` which we would have to [replicate as well.](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/materializations/configs.sql#L6).

I think then we need to modify the `ModelRunner` class to not do the incremental logic where it inspects the current models schema in the warehouse and modifies the predicted schema based on the `on_schema_change` setting for the model. You will probably have to pass wether the dry runner is `full_refresh` mode to the [constructor of NodeRunner](https://github.com/autotraderuk/dbt-dry-run/blob/804c7fbe7a84e350bd17cad7f333c9decb4d80a9/dbt_dry_run/node_runner/__init__.py#L17) and then use that boolean in `ModelRunner` [here
](https://github.com/autotraderuk/dbt-dry-run/blob/804c7fbe7a84e350bd17cad7f333c9decb4d80a9/dbt_dry_run/node_runner/model_runner.py#L114) to just use the predicted dry run schema if full refresh is enabled (Either via the CLI flag or in the model config)

Hope that makes sense! PRs for this welcome 👍

**Comment by davidsr2r** [comment]
Thanks so much! We do have a hack that will have to do for now, I ran the full refresh compilation and I changed the table types in the manifest.json to get dbt-dry-run to behave this way on incremental tables, however given that it's a hack we do plan on coming back to this as soon as we figure out how to completely plug all of the gaps, so I'd be keen to contribute as described then :)

**Comment by ccharlesgb** [comment]
We are going to work on this soon as a use case has come up that requires it.
