### ISSUE TITLE
Dry runner fails when partial compilation is done using dbt node-selection tags

### ISSUE THREAD

**Issue by praveen-prashant** [autotraderuk/dbt-dry-run#31]
We have quite a lot of tests for our models in our dbt repo and to reduce compilation time, we end up not compiling the tests in`development` environment

`dbt compile --exclude config.materialized:test`

However, when we run

`dbt-dry-run --report-path target/dbt-dry-run-report.json` for all tests it ends up throwing errors such as 

```
Node test.cpl_data.dbt_expectations_expect_column_values_to_not_be_null_sg_car_transaction_daily_customer_id.048603c1d9 was not compiled
```

i.e. the dry runner expects all the tests to be compiled. Is there a way for dry run to support the dbt node-selection tags like `exclude` and `select`?
https://docs.getdbt.com/reference/node-selection/syntax

**Comment by connor-charles** [comment]
Hey @praveen-prashant,

This is something that comes up a lot in our own dbt projects. The reason that this causes a dry run failure is because the package expects all enabled models to have been compiled to ensure that the project is fully covered by the protection that the dry runner gives against syntax errors. This prevents the dry run giving false confidence in a release if it processes a manifest where only a single model has been compiled and it reports a dry run success even though the project has barely been tested.

The dry runner supports tests as well so if you compile the manifest with the tests included you will get extra coverage against typos in test SQL and generic tests YAML.

Adding in support for `--exclude` and `--selector` would be great but we are waiting until the release of the dbt Python API to see if that makes including that feature a bit easier as parsing the syntax of selectors is quite complicated and would be a lot of work to replicate.

I think if a full compile is not an option for you, something that would be quite easy to do would be to get the dry runner to ignore models that are not compiled and have the default behaviour be overridden, something like `--skip-not-compiled` as a CLI flag perhaps? This causes a bit of weirdness if you have a dbt project that looks like this:

![image](https://user-images.githubusercontent.com/75633736/216968163-99a9bde1-01b2-4576-bd88-fa7fc7c2a3ca.png)

Because the dry runner won't be able to infer the schema of your 'staging' layer because it is not compiled so it will default to using whatever is in the target environment. But that doesn't affect your case here because tests are always at the end of the DAG of models in a dbt project.

**Comment by praveen-prashant** [comment]
Thanks for the detailed explanation @connor-charles.

Yes `--skip-not-compiled` would indeed do the job for us! Does that functionality exist already? If not would love your help to support it.

**Comment by connor-charles** [comment]
Cool, I have almost [got that working](https://github.com/autotraderuk/dbt-dry-run/commit/d687fe6199d7b4499b4c89f3cbdbaf15613ab752). 

The behaviour is a bit different to how I thought it would work. If you have a selectors that disable models at the downstream end of your dbt project, for example tests, or say you exclude your models right at the end of your DAG. Then the dry run will pass with `--skip-not-compiled`. 

However in the case of the diagram above it will still fail because in order to dry run `int_revenue` and `odp_finance_kpi` it can't proceed without the predicted schemas of the staging models.

This should cover your use case though and remove the weird ambiguity. Will try and finish it off when I have time later this week.
