### ISSUE TITLE
Failed Action: Release to PyPI on git tag

### ISSUE THREAD

**Issue by bbrewington** [autotraderuk/dbt-dry-run#5]
GH Actions run failed: https://github.com/autotraderuk/dbt-dry-run/actions/runs/2276126477

Not sure if this is causing it, but calling it out as fyi, there are 2 branches named `main`:

From https://github.com/autotraderuk/dbt-dry-run/network:

<img width="1115" alt="Screen Shot 2022-06-06 at 9 30 26 PM" src="https://user-images.githubusercontent.com/10573749/172276639-a9fd3431-36f5-46b4-95b5-38e1f0c3a6c7.png">

**Comment by connor-charles** [comment]
Hi @bbrewington,

I think this is ok, the failure was caused by me not including the PyPI token as a repository secret yet on the `autotraderuk` fork. On the next release it should run fine when `main` gets a new git tag as those secrets have been added to help automate the release process more.

Thanks for raising though!
Connor
