### ISSUE TITLE
dry run fail's when the view's are created on top of snapshot models

### ISSUE THREAD

**Issue by minhajpasha** [autotraderuk/dbt-dry-run#57]
We are creating the view's on top of snapshot model's for eg: view to filter latest records (WHERE dbt_valid_to IS NULL)  

The dbt dry run fails with below error for view's which refer's snapshot model's

Node model.test_project.customer_details_view failed with exception:
Can't insert SELECT literals for model.test_project.customer_details_view. Upstreams did not run with status: snapshot.test_project.customer_details_history : SKIPPED

Total 1 failures:
1	:	model.test_project.customer_details_view	:	UpstreamFailedException	:	ERROR
DRY RUN FAILURE!

**Comment by minhajpasha** [comment]
- get the previous status of manifest file : 
        gsutil cp gs://dbt-manifest-location/manifest.json manifest.json

- run the dbt compile to find only changed model's

     dbt compile --vars "{'dag_id': 'dbt_compile'}" --target dev  --select state:modified+ --state ./ && dbt-dry-run --skip-not-compiled  

We are trying to run : dbt-dry-run on only the model's that has been changed.

A change has been made to customer_details_view, but not to customer_details_history

please let me know if you need any more information

**Comment by ccharlesgb** [comment]
You need to compile the entire project for the dry runner to work. There's a longer explanation for why this is in #31 

Essentially because the dry runner builds up your dbt projects schema in the order of the DAG. In order to dry run your downstream view it needs to know what the predicted schema is of the upstream snapshot. These dry run queries are very low cost (I think they are free?)/quick so you don't save much if you only dry run changed models.

At Auto Trader we actually dry run our dbt projects in CI/CD (When there has been a change) but we also dry run every hour to pick up external changes that could affect the dbt project, stuff like external source's schema modifications (Columns get dropped in your sources), or permissions changes from terraform.
