### ISSUE TITLE
Missing total_bytes_processed

### ISSUE THREAD

**Issue by daniel-bartley** [autotraderuk/dbt-dry-run#58]
The primary reason I want to do a dry run is identify models that are inefficient.y

Surprised total_bytes_processed is not included in the payload

**Comment by ccharlesgb** [comment]
Hey, this is technically possible but would not be very accurate for incremental models.

The dry runner only runs the `SELECT` statement for the model. Incremental models are a bit more complicated because they do two queries:

1. Create a `_tmp` relation from the result of the model's `SELECT` statement.
2. Merge that `_tmp` table into the full table

The merge statement's `total_bytes_processed` would not be included in this case so the dry runner would be a 'lower limit' on the query cost.

We tend to solve this problem by monitoring query costs in production and uses quotas to ensure unoptimised queries don't cause too much damage. I'd welcome a PR on this though, you would need to include `total_bytes_processed` in the `DryRunResult` class for each node type I think and then output that in the report artefact.

**Comment by w1mvy** [comment]
@ccharlesgb 

Hi.   First of all, dbt-dry-run is useful and always helps me!!

I think this feature might be useful to use as a reference value.

> you would need to include total_bytes_processed in the DryRunResult class for each node type I think and then output that in the report artefact.

So, I implemented the above suggestions.

I will create a PR, can you review it?

https://github.com/w1mvy/dbt-dry-run/commit/42fdd95ba7f2bded3476dff87de335ec2283e904

**Comment by ccharlesgb** [comment]
Yes a PR would be appreciated for this one 👍
