### ISSUE TITLE
Unrecognized name _PARTITIONTIME for models with time ingestion partitioning

### ISSUE THREAD

**Issue by malikfm** [autotraderuk/dbt-dry-run#73]
I have two models, Model A (upstream) and B (downstream). Model A is an incremental model and it sets `"time_ingestion_partitioning": true` in its config. Model B selects from Model A using partition filter, e.g. `WHERE _PARTITIONTIME = 'YYYY-MM-DD HH:MM:SS'`.

dbt dry run fails on Model B with below error:
```
Node model.dbt_project.model_b failed with exception:
400 POST https://bigquery.googleapis.com/bigquery/v2/projects/gcp-project/jobs?prettyPrint=false: Unrecognized name: _PARTITIONTIME
```

**Comment by ccharlesgb** [comment]
This is because the dry runner does not add the `_PARTITIONTIME` column to the expected schema of Model A so it doesn't get included in the select literal.

Probably not that hard to fix, the [snapshot_runner](https://github.com/autotraderuk/dbt-dry-run/blob/a87aefc50d93073a19d261c1cabc98b0a74c66b0/dbt_dry_run/node_runner/snapshot_runner.py#L105) does something similar. We just need to say if the dry run is successful and `time_ingestion_partitioning == true` then add the `_PARTITIONTIME` column to the predicted schema. It would have to be just after this [line I think](https://github.com/autotraderuk/dbt-dry-run/blob/a87aefc50d93073a19d261c1cabc98b0a74c66b0/dbt_dry_run/node_runner/incremental_runner.py#L188)
